In [6]:
import numpy as np


def test():
    h_arr = [4,5,5,4,4,7,9]
    n1_arr = [0,0,1,1,2,3,3]
    heg_arr = np.zeros(7)

    for i in range(len(h_arr)):
            j = n1_arr[i]
            heg_arr[j] += h_arr[i]
            print(heg_arr)
    return heg_arr
print(test())

[4. 0. 0. 0. 0. 0. 0.]
[9. 0. 0. 0. 0. 0. 0.]
[9. 5. 0. 0. 0. 0. 0.]
[9. 9. 0. 0. 0. 0. 0.]
[9. 9. 4. 0. 0. 0. 0.]
[9. 9. 4. 7. 0. 0. 0.]
[ 9.  9.  4. 16.  0.  0.  0.]
[ 9.  9.  4. 16.  0.  0.  0.]
